#!/usr/bin/env ruby

require 'jrq'

require 'json'
require 'hashie'
require 'awesome_print'

_ = JSON.load(STDIN.read)
_ = Hashie::Mash.new(_)

if ARGV.length.zero?
  ap JSON.pretty_generate(_)
else
  ap eval(ARGV.first)
end
