#!/usr/bin/env ruby

require 'jrq'
require 'optparse'
require 'ostruct'

options = OpenStruct.new
oparser = OptionParser.new do |opts|
  opts.on('-r', '--raw', 'display output without quotations') do |raw|
    options.raw = raw
  end
end
args = oparser.parse!(ARGV)

Jrq::Cli.new.run(args, options)
